version: '2'
services:
    rowad-app:
        image: rowad
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rowad-postgresql:5432/rowad
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rowad-postgresql:
        extends:
            file: postgresql.yml
            service: rowad-postgresql
